---
- name: DEPLOY AS3 DEC
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
  vars_files: "/home/robin/creds/as3_creds.yaml"


  tasks:
  - name: Deploy AS3
    uri:
      url: https://18.168.66.20/mgmt/shared/appsvcs/declare/
      user: "{{ user_creds }}"
      password: "{{ user_pass }}"
      method: POST
      body: "{{ lookup('file','as3.json') }}"
      force_basic_auth: yes
      status_code: 200
      validate_certs: false
      body_format: json